Output demo.gif

Require ./spottui

Set Shell "bash"
Set FontSize 14
Set FontFamily "JetBrainsMono Nerd Font"
Set Width 1200
Set Height 980
Set Theme "TokyoNight"
Set WindowBar Colorful
Set Padding 20
Set TypingSpeed 50ms

Hide
Type "clear"
Enter
Sleep 500ms
Show

Type "./spottui"
Enter
Sleep 3s

Type "d"
Sleep 1s
Enter
Sleep 1s
Backspace
Sleep 1s

Type "/"
Sleep 500ms
Type "0N"
Sleep 500ms
Enter
Sleep 700ms
Enter
Sleep 2s

Type "j"
Sleep 300ms
Enter
Sleep 2s

Type "S"
Sleep 700ms
Type "never gonna give you up"
Sleep 500ms
Enter
Sleep 1s
Enter
Sleep 5s

Type "L"
Sleep 15s

Type "q"
Sleep 1s
